apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

resources:
  - ../../base
namePrefix: stage-

commonLabels:
  environment: stage

patches:
  - target:
      kind: Namespace
      name: gitops-demo
    patch: |-
      - op: replace
        path: /metadata/name
        value: stage
  - target:
      kind: Deployment
      name: gitops-demo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 300m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 192Mi
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: stage
  - target:
      kind: Service
      name: gitops-demo
    patch: |-
      - op: replace
        path: /metadata/name
        value: stage-gitops-demo
